### PR TITLE
[WIP] Refresh Primed

### PR DESCRIPTION
**Pull request by jedediah**
Added:

* Tanker TNT

Needs testing/ratings/tweaks:

* Zap
* cos^2(tnt)
* Donut Wars

### CODE REVIEW

**Comment by Ipskie** [comment]
Zap and cos 2 I don't think belong, the gameplay is very uniform and does not progress much as the match goes on, leading to uniform, boring gameplay.

Suggestions: 
 - Remove or improve Retaliation, specifically to make it more cannon friendly (more cannon parts, less redstone, more water)
 - I can outfit revenge for pub, if anyone supports it
 - Change datastation to a TDM, IMO it would play better that way

+1 to tanker

**Comment by Z3R0Z3R0Z3R0** [comment]
Tanker TNT cannons and plays poorly, it should not be added.

Cos^2 is a very repetitive map and suffers all the se flaws of cos. It's boring to play, and should absolutely not be added.

Zap isn't even about tnt, cannons are either useless or extremely op, 2 of the teams have a huge advantage due to east/west tnt that the other teams don't, and it tales away ftom classic pvp by not having bows or swords.

**Comment by Z3R0Z3R0Z3R0** [comment]
#375 I think this is the best way to improve primed. All the gimmick maps that get good ratings and are generally enjoyed go to one place (not all maps there would have tnt to get more diversity), and the competitive style old fashioned tnt maps stay on primed.

**Comment by CoWinkKeyDinkInc** [comment]
cos^2(tnt) seems just like csc(tnt) is that the lack of walls make building platforms more harder, especially with dispenser bombs.  I think that cos^2 should have a bit more platforms at different heights.

**Comment by thestrangeboy1** [comment]
I think Dangerous Cargo would be a good map to add in. It's very similar to SSB and due to how low SSB's ratings are currently, I think it would be a good replacement.

Athirk also plays alright too. It has a huge void gap which is my only concern because it makes cannoning require redstone for a large amount of charge to get the TNT across.

In general, I think we need to make monuments a lot harder to get in some of these maps. I mean you literally just have to spam TNT around 6 blocks and you got the monument completed. We should consider changing the materials of all monuments and how exactly they're positioned or how much of a monument there is to break. A lot of these maps now are being rushed in less than 5 minutes and I think we need to change that and make matches a bit longer.

**Comment by HardstyleRaver2** [comment]
I don't agree with adding Zap to Primed because of how it plays. The last time I played that map, I was met with 0 resistance from the other teams while I was using cannons. The bridgers were completely helpless. The match felt boring because of it. Like Zero said, the map suffers from TNT's directional bias, since the map is shaped like a square with four teams taking up each side. However, that issue has been fixed in 1.8.

If I remembered correctly, cos^2(tnt) has a spawn system similar to the Attackers' spawn system in BoomBox, and there doesn't appear to be any other significant difference when compared to cos(tnt). In my opinion, I don't think it should be added.

Tanker TNT is okay in my opinion. Although, I do think that the void gap should be lessened.

Here is what I think should be added to Primed:
1. Totally War II. I'm not sure why it was removed, but I do like the map when it was on Primed. It rarely gets rushed, and there are plenty of places to aim with your cannon if chests' invulnerability to TNT is disabled.
2. Dangerous Cargo. 
3. Streamline. It is a decent map in my opinion. However, it could be considered to be too small; even though, it has the same team sizes as BoomBox.
4. Athirk. It just needs more cannon supplies.

Here is what I think should be prioritized for testing:
1. Streamline II. I would recommend testing it if Streamline is considered too small for Primed.
2. Explosive Vengeance v2.0.0. I'm not sure if that version plays better than the previous vedsions, but it's worth a try.
3. Relic.

By the way, I would recommend that you make a CTF for Primed when all of the servers are updated to 1.8. I'm curious of how it will play out.

**Comment by jedediah** [comment]
How about Donut Wars?

**Comment by Z3R0Z3R0Z3R0** [comment]
@jebediah From what I've seen that map is confined to 2 main cannon lanes that are dominated by the first player to set one up. It could work, and frankly I think it fits the objective of the server better than some of the maps currently on primed, but it's not the greatest example of high competitive DTC/M that primed is often a representation of.

**Comment by CoWinkKeyDinkInc** [comment]
@jedediah I think that Donut Wars might work better on Mini.

**Comment by Ipskie** [comment]
@jedediah what hive said, it doesn't work too well of public, the supplies get rekt really fast and from what I've seen the stalemates that often ensue are painful and boring. Basically an SSB that works less well (and is less loved)

**Comment by Electroid** [comment]
Not relevant anymore.

**Pull request closed without merging**
