### PR TITLE
Add BlockRAGE to Conquer

### PR DESCRIPTION
**Pull request by RubeVi**

### CODE REVIEW

**Comment by matic0basle** [comment]
The map is already on multiple Mini servers AFAIK. There is no need for it to be on Conquer. I am heavily against this.

**Comment by Ipskie** [comment]
Rage TDM's IMO don't belong, there's no need for this to happen

**Comment by Z3R0Z3R0Z3R0** [comment]
@Ipskie this 100%

**Comment by CaptainElliott** [comment]
Personally I do not think that RageTDMs belong on concur and neither do a few others. 
Also in commits and PR titles do not make your own tags

**Comment by RubeGamerV** [comment]
@matic0basle only mini03 have it, so if other server have BlockRAGE there are always offline

**Comment by matic0basle** [comment]
@RubeGamerV Still against it because it just wouldn't fit and theres already BlockBlock

**Comment by Tapetepato** [comment]
I don't usually play on Conquer, but i think it needs more Rage TDMS, it's kinda boring atm. +1

**Comment by Electroid** [comment]
It's in rotations enough.

**Pull request closed without merging**
